/**
 * Core data types for OpenThreads.
 *
 * These types model the six primary collections:
 * channels, recipients, threads, turns, routes, tokens.
 */

// ---------------------------------------------------------------------------
// Channel
// ---------------------------------------------------------------------------

/** Platform type for a communication channel. */
export type ChannelPlatform =
  | 'slack'
  | 'discord'
  | 'telegram'
  | 'whatsapp'
  | 'teams'
  | 'google-chat'
  | string;

/**
 * A registered communication channel (e.g. a Slack bot, a Telegram bot).
 * Represents the interface with the human world (senders).
 */
export interface Channel {
  /** Unique identifier for the channel (e.g. "slack-main"). */
  channelId: string;
  /** Platform type. */
  platform: ChannelPlatform;
  /** Human-readable display name. */
  name: string;
  /** Channel-scoped API key (ot_ch_sk_...) for direct sends. */
  apiKey: string;
  /** Platform-specific configuration (bot tokens, webhook secrets, etc.). */
  config: Record<string, unknown>;
  /** Whether this channel is active and accepting messages. */
  active: boolean;
  createdAt: Date;
  updatedAt: Date;
}

// ---------------------------------------------------------------------------
// Recipient
// ---------------------------------------------------------------------------

/**
 * An external system that consumes messages and responds (agent, API, service).
 * Represents the interface with the machine world.
 */
export interface Recipient {
  /** Unique identifier for the recipient. */
  recipientId: string;
  /** Human-readable display name. */
  name: string;
  /** URL to POST outbound envelopes to. */
  webhookUrl: string;
  /** Optional shared secret for HMAC webhook signature verification. */
  webhookSecret?: string;
  /** Whether this recipient is active. */
  active: boolean;
  /** Additional metadata. */
  metadata?: Record<string, unknown>;
  createdAt: Date;
  updatedAt: Date;
}

// ---------------------------------------------------------------------------
// Thread
// ---------------------------------------------------------------------------

/**
 * A conversation identified by a threadId generated by OpenThreads.
 *
 * Three scenarios:
 * - Channel with native threads (Slack, Discord): 1:1 mapping with nativeThreadId.
 * - Channel without threads (Telegram DM, WhatsApp): virtual threads via reply chains.
 * - Messages outside threads: belong to the channel/target's "main thread".
 */
export interface Thread {
  /** Unique identifier (ot_thr_...). */
  threadId: string;
  /** ID of the channel this thread belongs to. */
  channelId: string;
  /** Native platform thread/message ID, if applicable. */
  nativeThreadId?: string;
  /** Target group or user ID within the channel (e.g. Slack channelId, Telegram chatId). */
  targetId: string;
  /** True if this is the synthetic "main thread" for messages outside native threads. */
  isMain: boolean;
  /** Optional metadata about the thread. */
  metadata?: Record<string, unknown>;
  createdAt: Date;
  updatedAt: Date;
}

// ---------------------------------------------------------------------------
// Turn
// ---------------------------------------------------------------------------

/** The source context of an incoming message. */
export interface TurnSource {
  channelId: string;
  sender: {
    id: string;
    name: string;
  };
  /** Native message ID within the platform (for reply chaining). */
  nativeMessageId?: string;
}

/**
 * An individual interaction within a thread: one sender-message → recipient-response cycle.
 */
export interface Turn {
  /** Unique identifier (ot_turn_...). */
  turnId: string;
  /** The thread this turn belongs to. */
  threadId: string;
  /** Inbound message payload (Chat SDK or A2H format). */
  inboundMessage: unknown;
  /** Source context (channel, sender). */
  source: TurnSource;
  /** Pre-computed replyTo URL for this turn. */
  replyTo: string;
  /** Outbound response from the recipient, once received. */
  outboundResponse?: unknown;
  /** Timestamp when the inbound message was received. */
  timestamp: Date;
  createdAt: Date;
  updatedAt: Date;
}

// ---------------------------------------------------------------------------
// Route
// ---------------------------------------------------------------------------

/**
 * Criteria for matching incoming messages to a route.
 * All specified fields must match (logical AND). Omitted fields are wildcards.
 */
export interface RouteCriteria {
  /** Match by channel ID. */
  channelId?: string;
  /** Match by target group/user ID. */
  targetId?: string;
  /** Match only direct messages. */
  isDM?: boolean;
  /** Match only messages that mention the bot. */
  mentionOnly?: boolean;
  /** Match by sender ID. */
  senderId?: string;
  /** Match message content against a regex pattern. */
  contentPattern?: string;
  /** Match a specific thread. */
  threadId?: string;
}

/**
 * A routing rule that maps incoming messages (sender via channel) to outbound recipients.
 */
export interface Route {
  /** Unique identifier for the route. */
  routeId: string;
  /** ID of the recipient to forward matching messages to. */
  recipientId: string;
  /** Matching criteria. */
  criteria: RouteCriteria;
  /** Whether this route is active. */
  active: boolean;
  /** Higher priority routes are evaluated first. */
  priority: number;
  /** Human-readable description. */
  description?: string;
  createdAt: Date;
  updatedAt: Date;
}

// ---------------------------------------------------------------------------
// Token
// ---------------------------------------------------------------------------

/**
 * An ephemeral authentication token embedded in replyTo URLs.
 * Scoped to a specific thread/turn, with a configurable TTL (default 24h).
 * MongoDB TTL index on `expiresAt` auto-expires documents.
 */
export interface Token {
  /** Unique identifier for the token record. */
  tokenId: string;
  /** The token value embedded in the URL (ot_tk_...). */
  value: string;
  /** The channel this token is scoped to. */
  channelId: string;
  /** The thread this token is scoped to. */
  threadId: string;
  /** The turn this token is scoped to, if applicable. */
  turnId?: string;
  /** Expiry time; MongoDB TTL index auto-expires documents after this. */
  expiresAt: Date;
  createdAt: Date;
}
