/**
 * Core data model types for OpenThreads.
 *
 * Channel       — registration of an external messaging account/channel (Slack bot, Telegram bot, etc.)
 * Recipient     — external system that consumes messages and responds (agent, API, service)
 * Route         — routing rule that maps incoming messages to outbound recipients
 * InboundMessage — metadata for an incoming message used by the router
 * Thread        — conversation identified by a threadId generated by OpenThreads
 * Turn          — individual sender-message → recipient-response cycle within a thread
 */

/** Supported messaging platform types. */
export type ChannelType =
  | "slack"
  | "discord"
  | "telegram"
  | "whatsapp"
  | "teams"
  | "googlechat"
  | string;

/** A registered messaging channel (e.g. a Slack bot, a Telegram bot). */
export interface Channel {
  /** Unique identifier. */
  id: string;
  /** Human-readable label. */
  name: string;
  /** Platform type. */
  type: ChannelType;
  /** Whether this channel is active. */
  enabled: boolean;
}

/** An external system that receives outbound webhooks and may send replies. */
export interface Recipient {
  /** Unique identifier. */
  id: string;
  /** Human-readable label. */
  name: string;
  /** Outbound webhook URL. */
  webhookUrl: string;
  /** Whether this recipient is active. */
  enabled: boolean;
}

/**
 * Criteria that an inbound message must satisfy for the route to match.
 *
 * Each field accepts:
 *   - `undefined`                → matches any value (wildcard)
 *   - a single string            → exact match, or glob pattern (`*`, `?` wildcards)
 *   - an array of strings        → OR logic: matches if any element matches
 *
 * Boolean fields:
 *   - `undefined`                → matches regardless of flag value
 *   - `true` / `false`           → must equal that value exactly
 *
 * All specified criteria must match (AND logic across fields).
 */
export interface RouteCriteria {
  /**
   * Match by channel id(s).
   * Supports glob patterns (e.g. `"slack-*"`).
   */
  channel?: string | string[];

  /**
   * Match by the target identifier within the channel (group id, user id, etc.).
   * Supports glob patterns.
   */
  target?: string | string[];

  /**
   * Match by sender identifier.
   * Supports glob patterns (e.g. `"U*"` for any Slack user id).
   */
  sender?: string | string[];

  /**
   * Match against message content.
   * Supports glob patterns (e.g. `"deploy *"`, `"*help*"`).
   */
  content?: string | string[];

  /**
   * If `true`, only messages inside a thread match.
   * If `false`, only top-level messages match.
   * `undefined` matches either.
   */
  isThread?: boolean;

  /**
   * If `true`, only messages that mention the bot match.
   * If `false`, only messages without a mention match.
   * `undefined` matches either.
   */
  isMention?: boolean;

  /**
   * If `true`, only direct-message conversations match.
   * If `false`, only non-DM messages match.
   * `undefined` matches either.
   */
  isDM?: boolean;
}

/** A routing rule mapping inbound messages that satisfy its criteria to one or more recipients. */
export interface Route {
  /** Unique identifier. */
  id: string;
  /** Human-readable label. */
  name: string;
  /** Matching criteria. All specified fields must match (AND). */
  criteria: RouteCriteria;
  /**
   * Ids of recipients that should receive matching messages (fan-out).
   * Multiple recipients are all notified in order.
   */
  recipientIds: string[];
  /**
   * Priority used to order matched routes.
   * Higher values take precedence. Defaults to 0.
   */
  priority: number;
  /** Whether this route is active. Disabled routes are never matched. */
  enabled: boolean;
}

/** Metadata for an inbound message, used as input to the router. */
export interface InboundMessage {
  /** Id of the channel the message arrived on. */
  channel: string;
  /** Target identifier within the channel (group/channel id, user id for DMs, etc.). */
  target: string;
  /** Identifier of the sender. */
  sender: string;
  /** Raw text content of the message. */
  content: string;
  /** True if the message is inside a thread. */
  isThread: boolean;
  /** True if the message mentions the bot. */
  isMention: boolean;
  /** True if the message is a direct message to the bot. */
  isDM: boolean;
}

/** A conversation managed by OpenThreads, identified by a generated threadId. */
export interface Thread {
  /** Unique thread identifier generated by OpenThreads (e.g. `ot_thr_abc123`). */
  threadId: string;
  /** Id of the channel this thread belongs to. */
  channelId: string;
  /** Target identifier within the channel (group, user, etc.). */
  target: string;
  /** ISO-8601 timestamp of the first message in the thread. */
  createdAt: string;
  /** ISO-8601 timestamp of the most recent activity. */
  updatedAt: string;
}

/** A single sender-message → recipient-response cycle within a thread. */
export interface Turn {
  /** Unique turn identifier generated by OpenThreads (e.g. `ot_turn_001`). */
  turnId: string;
  /** Thread this turn belongs to. */
  threadId: string;
  /** Sender identifier. */
  sender: string;
  /** Raw message content from the sender. */
  message: string;
  /** ISO-8601 timestamp of this turn. */
  createdAt: string;
}
